bbb: option to install greenlight

diff --git a/bbb.yaml b/bbb.yaml
--- a/bbb.yaml
+++ b/bbb.yaml
@@ -19,6 +19,11 @@ parameters:
     label: Cliente demo de BBB
     description: Instalar cliente demo de BBB
     default: ""
+  bbb_greenlight:
+    type: string
+    label: Cliente Greenlight de BBB
+    description: Instalar cliente Greenlight de BBB
+    default: ""
   private_net:
     type: string
     label: Nombre de la red privada
@@ -110,6 +115,12 @@ resources:
         IP=${bbb_ip}
         SERVLET_CONTAINER=tomcat7
         SERVLET_DIR=/var/lib/$SERVLET_CONTAINER/webapps
+
+        # functions
+        error() {
+          say "$1" >&2
+          exit 1
+        }
 
         # Configuracion DNS
         if ! [[ -z ${bbb_domain+x} ]] && ! [[ -z ${bbb_domain} ]]; then
@@ -233,9 +244,94 @@ resources:
         # start bbb
         bbb-conf --clean
 
+        # Instalar greenlight si es requerido
+        # From bbb-install
+        if ! [[ -z ${is_bbb_greenlight:-} ]]; then
+          DEBIAN_FRONTEND=noninteractive LC_CTYPE=C.UTF-8 apt-get install -y \
+            openssl apt-transport-https \
+            ca-certificates \
+            curl \
+            gnupg-agent \
+            software-properties-common
+          # Install Docker
+          if ! apt-key list | grep -q Docker; then
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
+          fi
+          if ! dpkg -l | grep -q docker-ce; then
+            add-apt-repository \
+              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
+              $(lsb_release -cs) \
+              stable"
+            apt-get update
+            DEBIAN_FRONTEND=noninteractive LC_CTYPE=C.UTF-8 apt-get install -y docker-ce
+          fi
+          if ! which docker; then error "Docker did not install"; fi
+          if [ ! -x /usr/local/bin/docker-compose ]; then
+            curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            chmod +x /usr/local/bin/docker-compose
+          fi
+
+          if [ ! -d ~/greenlight ]; then
+            mkdir -p ~/greenlight
+          fi
+
+          # This will trigger the download of Greenlight docker image (if needed)
+          SECRET_KEY_BASE=$(docker run --rm bigbluebutton/greenlight:v2 bundle exec rake secret)
+
+          if [ ! -f ~/greenlight/.env ]; then
+            docker run --rm bigbluebutton/greenlight:v2 cat ./sample.env > ~/greenlight/.env
+          fi
+
+          BIGBLUEBUTTON_URL=$(cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep -v '#' | sed -n '/^bigbluebutton.web.serverURL/{s/.*=//;p}')/bigbluebutton/
+          BIGBLUEBUTTON_SECRET=$(cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties   | grep -v '#' | grep securitySalt | cut -d= -f2)
+
+          # Update Greenlight configuration file in ~/greenlight/env
+          sed -i "s|SECRET_KEY_BASE=.*|SECRET_KEY_BASE=$SECRET_KEY_BASE|"                   ~/greenlight/.env
+          sed -i "s|.*BIGBLUEBUTTON_ENDPOINT=.*|BIGBLUEBUTTON_ENDPOINT=$BIGBLUEBUTTON_URL|" ~/greenlight/.env
+          sed -i "s|.*BIGBLUEBUTTON_SECRET=.*|BIGBLUEBUTTON_SECRET=$BIGBLUEBUTTON_SECRET|"  ~/greenlight/.env
+
+          # need_pkg bbb-webhooks
+
+          if [ ! -f /etc/bigbluebutton/nginx/greenlight.nginx ]; then
+            docker run --rm bigbluebutton/greenlight:v2 cat ./greenlight.nginx | tee /etc/bigbluebutton/nginx/greenlight.nginx
+            cat > /etc/bigbluebutton/nginx/greenlight-redirect.nginx << HERE
+        location = / {
+          return 307 /b;
+        }
+        HERE
+            systemctl restart nginx
+          fi
+
+          if ! gem list | grep -q java_properties; then
+            gem install jwt java_properties
+          fi
+
+          if [ ! -f ~/greenlight/docker-compose.yml ]; then
+            docker run --rm bigbluebutton/greenlight:v2 cat ./docker-compose.yml > ~/greenlight/docker-compose.yml
+          fi
+
+          # change the default passwords
+          PGPASSWORD=$(openssl rand -hex 8)
+          sed -i "s/POSTGRES_PASSWORD=password/POSTGRES_PASSWORD=$PGPASSWORD/g" ~/greenlight/docker-compose.yml
+          sed -i "s/DB_PASSWORD=password/DB_PASSWORD=$PGPASSWORD/g" ~/greenlight/.env
+
+          # Remove old containers
+          if docker ps | grep -q greenlight_db_1; then
+            docker rm -f greenlight_db_1
+          fi
+          if docker ps | grep -q greenlight-v2; then
+            docker rm -f greenlight-v2
+          fi
+
+          if ! docker ps | grep -q greenlight; then
+            docker-compose -f ~/greenlight/docker-compose.yml up -d
+            sleep 5
+          fi
+        fi
+
         # Instalar demo si es requerido
         if ! [[ -z ${is_bbb_demo:-} ]]; then
-          DEBIAN_FRONTEND=noninteractive apt-get -y install bbb-demo
+          DEBIAN_FRONTEND=noninteractive LC_CTYPE=C.UTF-8 apt-get install -y install bbb-demo
           if [ -f /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp ]; then
             sed -i "s@^String BigBlueButtonURL.*@String BigBlueButtonURL = \"https://${HOST}/bigbluebutton/\";@" /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
           else
@@ -250,6 +346,7 @@ resources:
 
         [ -z "${bbb_ip:-}" ] || sed -i  "/^# heat_vars/a bbb_ip='${bbb_ip}'" $script
         [ -z "${is_bbb_demo:-}" ] || sed -i   "/^# heat_vars/a is_bbb_demo='${is_bbb_demo}'" $script
+        [ -z "${is_bbb_greenlight:-}" ] || sed -i   "/^# heat_vars/a is_bbb_greenlight='${is_bbb_greenlight}'" $script
         [ -z "${bbb_domain:-}" ] || sed -i "/^# heat_vars/a bbb_domain='${bbb_domain}'" $script
         [ -z "${bbb_recording_hostname:-}" ] || sed -i "/^# heat_vars/a bbb_recording_hostname='${bbb_recording_hostname}'" $script
         [ -z "${bbb_nfs_mount:-}" ] || sed -i "/^# heat_vars/a bbb_nfs_mount='${bbb_nfs_mount}'" $script
@@ -260,7 +357,7 @@ resources:
         $script > /tmp/bbb-heat.log
 
         # check status
-        bbb-conf --status | grep failed && exit 1
+        bbb-conf --status | grep failed && error "bbb-status failed"
 
         # Devolver url y llave compartida
         bbb-conf --secret | grep -i url: | awk '{print $2}' > ${heat_outputs_path}.bbb_url
@@ -275,6 +372,7 @@ resources:
       input_values:
         bbb_ip: {get_attr: [bbb-server, networks, {get_param: public_net}, 0]}
         is_bbb_demo: {get_param: bbb_demo}
+        is_bbb_greenlight: {get_param: bbb_greenlight}
         bbb_domain: {get_param: bbb_domain}
         bbb_recording_hostname: {get_param: bbb_recording_hostname}
         bbb_nfs_mount: {get_param: bbb_nfs_mount}
