BBB v1.1 y Ubuntu Xenial

diff --git a/bbb.yaml b/bbb.yaml
--- a/bbb.yaml
+++ b/bbb.yaml
@@ -7,16 +7,15 @@ parameters:
     # type: string
   key_name:
     type: string
-    label: Nombre de la llave privada
-    description: Nombre de la llave privada para usar en la maquina virtual
   flavor:
     type: string
-    label: Nombre del sabor
-    description: Nombre del sabor para la maquina virtual
   image:
     type: string
-    label: Nombre de la imagen de disco
-    description: Nombre de la imagen de disco para iniciar la maquina virtual
+  bbb_demo:
+    type: string
+    label: Cliente demo de BBB
+    description: Instalar cliente demo de BBB
+    default: No
   private_net:
     type: string
     label: Nombre de la red privada
@@ -45,8 +44,8 @@ resources:
         osFamily: "unix"
         osName: "Linux"
         distro: "Ubuntu"
-        osVersion: "14.04"
-        tags: "bbb,ubuntu,trusty"
+        osVersion: "16.04"
+        tags: "bbb,ubuntu,xenial"
         # Para ubicar en diferentes hipervisores
         # scheduler_hints:
           # group: {Ref: haproxy_cluster}
@@ -60,6 +59,9 @@ resources:
       - name: shared_key_in
         description: Llave compartida de BBB
         default: No
+      - name: is_bbb_demo
+        description: Instalar cliente bbb demo
+        default: No
       - name: bbb_ip
         description: IP del nodo de BBB
       outputs:
@@ -72,23 +74,22 @@ resources:
         set -eu
         set -o pipefail
 
-        # Variables
-        #shared_key_in="False"
-        #bbb_ip="172.16.49.197"
+        echo "${bbb_ip} $(hostname)" >> /etc/hosts
+        HOST=${bbb_ip}
 
-        # Workaround syslog sin registros
-        service rsyslog restart
-
-        # Permite utilizar apt de forma desatendida
-        export DEBIAN_FRONTEND=noninteractive
+        if ! [ -z ${bbb_host+x} ]; then
+          echo "${bbb_ip} ${bbb_host}" >> /etc/hosts
+          HOST=${bbb_ip}
+        fi
 
         # Asignar llave compartida y devolver como parametro
         if ! [[ ${shared_key_in} == "False" ]]; then
             bbb-conf --setsecret ${shared_key_in}
         fi
 
-        # Activar audio WebRTC
-        bbb-conf --enablewebrtc
+        # Eliminar perfiles ipv6 de freesweitch (solo ipv4)
+        rm -rf /opt/freeswitch/etc/freeswitch/sip_profiles/*ipv6*
+        sed -i "s@.*<param name=\"listen-ip\"@    <param name=\"listen-ip\" value=\"127.0.0.1\"/>@" /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
 
         # Actualizar IP y reiniciar servicios. En caso de estar detras de un balanceador acá debería ir el dns del frontend
         ###################### Segmento de /usr/bin/bbb-conf ##################################
@@ -111,57 +112,96 @@ resources:
         # Author(s):
         #       Fred Dixon <ffdixon@bigbluebutton.org>
         #       Sebastian Schneider <seb.sschneider@gmail.com>
-        HOST=${bbb_ip}
-        redis_host=${bbb_ip}
+        #       Ghazi Triki <ghazi.nocturne@gmail.com>
+        redis_host=${HOST}
         SERVLET_CONTAINER=tomcat7
         SERVLET_DIR=/var/lib/$SERVLET_CONTAINER/webapps
+        FREESWITCH_VARS=/opt/freeswitch/conf/vars.xml
+        FREESWITCH_EXTERNAL=/opt/freeswitch/conf/sip_profiles/external.xml
+        TO_BACKUP="N"
+
         if cat /var/www/bigbluebutton/client/conf/config.xml | grep "ChatModule" | grep -q https; then
-            PROTOCOL_HTTP=https
-            PROTOCOL_RTMP=rtmp
+        	PROTOCOL_HTTP=https
+        	PROTOCOL_RTMP=rtmp
         else
-            PROTOCOL_HTTP=http
-            PROTOCOL_RTMP=rtmp
+        	PROTOCOL_HTTP=http
+        	PROTOCOL_RTMP=rtmp
         fi
+        check_and_backup () {
+        	# can we write to the configuration file?
+        	if [ ! -w $1 ]; then
+        		echo "Cannot write to $1!"
+        		exit 1
+        	fi
+
+        	# let's see if we need a copy
+        	if [ "$TO_BACKUP" = "Y" ]; then
+        		cp $1 $1.bak
+        		TO_BACKUP="N"
+        	fi
+        }
+        change_var_value () {
+        	check_and_backup $1
+        	sed -i "s<^[[:blank:]#]*\(${2}\).*<\1=${3}<" $1
+        }
         change_yml_value () {
-            sed -i "s<^[[:blank:]#]*\(${2}\):[ ].*<\1: ${3}<" $1
+          sed -i "s<^[[:blank:]#]*\(${2}\):[ ].*<\1: ${3}<" $1
         }
         #
         # Just use the IP for port test in /var/www/bigbluebutton/client/conf/config.xml
         #
         echo "Assigning $HOST for testing for firewall in /var/www/bigbluebutton/client/conf/config.xml"
-        sudo sed -i "s/porttest host=\(\"[^\"]*\"\)/porttest host=\"$HOST\"/g" /var/www/bigbluebutton/client/conf/config.xml
+        sed -i "s/porttest host=\(\"[^\"]*\"\)/porttest host=\"$HOST\"/g" /var/www/bigbluebutton/client/conf/config.xml
 
         echo "Assigning $HOST for rtmp:// in /var/www/bigbluebutton/client/conf/config.xml"
-        sudo sed -i "s/rtmp[s]*:\/\/\([^\"\/]*\)\([\"\/]\)/$PROTOCOL_RTMP:\/\/$HOST\2/g" /var/www/bigbluebutton/client/conf/config.xml
+        sed -i "s/rtmp[s]*:\/\/\([^\"\/]*\)\([\"\/]\)/$PROTOCOL_RTMP:\/\/$HOST\2/g" /var/www/bigbluebutton/client/conf/config.xml
 
         echo "Assigning $HOST for servername in /etc/nginx/sites-available/bigbluebutton"
-        sudo sed -i "s/server_name  .*/server_name  $HOST;/g" /etc/nginx/sites-available/bigbluebutton
+        sed -i "s/server_name  .*/server_name  $HOST;/g" /etc/nginx/sites-available/bigbluebutton
 
         #
         # Update configuration for BigBlueButton client
         #
         echo "Assigning $HOST for http[s]:// in /var/www/bigbluebutton/client/conf/config.xml"
-        sudo sed -i "s/http[s]*:\/\/\([^\"\/]*\)\([\"\/]\)/$PROTOCOL_HTTP:\/\/$HOST\2/g"  /var/www/bigbluebutton/client/conf/config.xml
+        sed -i "s/http[s]*:\/\/\([^\"\/]*\)\([\"\/]\)/$PROTOCOL_HTTP:\/\/$HOST\2/g"  /var/www/bigbluebutton/client/conf/config.xml
 
         echo "Assigning $HOST for publishURI in /var/www/bigbluebutton/client/conf/config.xml"
-        sudo sed -i "s/publishURI=\"[^\"]*\"/publishURI=\"$HOST\"/" /var/www/bigbluebutton/client/conf/config.xml
+        sed -i "s/publishURI=\"[^\"]*\"/publishURI=\"$HOST\"/" /var/www/bigbluebutton/client/conf/config.xml
 
         #
         # Update configuration for BigBlueButton web app
         #
         echo "Assigning $HOST for web application URL in ${SERVLET_DIR}/bigbluebutton/WEB-INF/classes/bigbluebutton.properties"
 
-        sudo sed -i "s/bigbluebutton.web.serverURL=http[s]*:\/\/.*/bigbluebutton.web.serverURL=$PROTOCOL_HTTP:\/\/$HOST/g" \
-            ${SERVLET_DIR}/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
+        sed -i "s/bigbluebutton.web.serverURL=http[s]*:\/\/.*/bigbluebutton.web.serverURL=$PROTOCOL_HTTP:\/\/$HOST/g" \
+        	${SERVLET_DIR}/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
 
-        # 3 paramenter: the file, the variable name, the new value
-        # echo "Assigning $HOST for FreeSWITCH Event Socket Layer URL in ${SERVLET_DIR}/bigbluebutton/WEB-INF/classes/bigbluebutton.properties"
-        # change_var_ip /usr/share/red5/webapps/bigbluebutton/WEB-INF/bigbluebutton.properties esl.host $HOST
-
-        # cat ${SERVLET_DIR}/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
+        change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties streamBaseUrl rtmp://$HOST/screenshare
+        change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpUrl $PROTOCOL_HTTP://$HOST/screenshare
+        change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpFile $PROTOCOL_HTTP://$HOST/screenshare/screenshare.jnlp
 
         if ! grep -q server_names_hash_bucket_size /etc/nginx/nginx.conf; then
-            sudo sed -i "s/gzip  on;/gzip  on;\n    server_names_hash_bucket_size  64;/g" /etc/nginx/nginx.conf
+        	sed -i "s/gzip  on;/gzip  on;\n    server_names_hash_bucket_size  64;/g" /etc/nginx/nginx.conf
+        fi
+
+        #
+        # Update bbb-apps-akka
+        #
+        echo "Assigning $HOST for web application URL in /usr/share/bbb-apps-akka/conf/application.conf"
+
+        if [ -f /usr/share/bbb-apps-akka/conf/application.conf ]; then
+          sed -i  "s/bbbWebAPI[ ]*=[ ]*\"[^\"]*\"/bbbWebAPI=\"${PROTOCOL_HTTP}:\/\/$HOST\/bigbluebutton\/api\"/g" \
+            /usr/share/bbb-apps-akka/conf/application.conf
+          sed -i "s/bbbWebHost[ ]*=[ ]*\"[^\"]*\"/bbbWebHost=\"$HOST\"/g" \
+            /usr/share/bbb-apps-akka/conf/application.conf
+          sed -i "s/deskshareip[ ]*=[ ]*\"[^\"]*\"/deskshareip=\"$HOST\"/g" \
+            /usr/share/bbb-apps-akka/conf/application.conf
+          sed -i  "s/defaultPresentationURL[ ]*=[ ]*\"[^\"]*\"/defaultPresentationURL=\"${PROTOCOL_HTTP}:\/\/$HOST\/default.pdf\"/g" \
+            /usr/share/bbb-apps-akka/conf/application.conf
+          # Fix to ensure application.conf has the latest shared secret
+          SECRET=$(cat ${SERVLET_DIR}/bigbluebutton/WEB-INF/classes/bigbluebutton.properties | grep -v '#' | grep securitySalt | cut -d= -f2);
+          sed -i "s/sharedSecret[ ]*=[ ]*\"[^\"]*\"/sharedSecret=\"$SECRET\"/g" \
+            /usr/share/bbb-apps-akka/conf/application.conf
         fi
 
         #
@@ -169,58 +209,79 @@ resources:
         #
 
         if [ -f ${SERVLET_DIR}/demo/bbb_api_conf.jsp ]; then
-            echo "Assigning $HOST for api demos in ${SERVLET_DIR}/demo/bbb_api_conf.jsp"
-            sudo sed -i "s/BigBlueButtonURL = \"http[s]*:\/\/\([^\"\/]*\)\([\"\/]\)/BigBlueButtonURL = \"$PROTOCOL_HTTP:\/\/$HOST\2/g" \
-                ${SERVLET_DIR}/demo/bbb_api_conf.jsp
+        	echo "Assigning $HOST for api demos in ${SERVLET_DIR}/demo/bbb_api_conf.jsp"
+        	sed -i "s/BigBlueButtonURL = \"http[s]*:\/\/\([^\"\/]*\)\([\"\/]\)/BigBlueButtonURL = \"$PROTOCOL_HTTP:\/\/$HOST\2/g" \
+        		${SERVLET_DIR}/demo/bbb_api_conf.jsp
         fi
 
 
-        if [ -f ${SERVLET_DIR}/lti/WEB-INF/classes/lti.properties ]; then
-            echo "Assigning $HOST for LTI integration in ${SERVLET_DIR}/lti/WEB-INF/classes/lti.properties"
-            # We don't wat to guess on http/https as the lti endpoint may be a different BigBlueButton server
-            sed -i "s/bigbluebuttonURL=http:\/\/.*/bigbluebuttonURL=http:\/\/$HOST\/bigbluebutton/g" \
-                ${SERVLET_DIR}/lti/WEB-INF/classes/lti.properties
-            sed -i "s/bigbluebuttonURL=https:\/\/.*/bigbluebuttonURL=https:\/\/$HOST\/bigbluebutton/g" \
-                ${SERVLET_DIR}/lti/WEB-INF/classes/lti.properties
-            sed -i "s/ltiEndPoint=.*/ltiEndPoint=$HOST/g" \
-                ${SERVLET_DIR}/lti/WEB-INF/classes/lti.properties
+        if [ -f ${SERVLET_DIR}/lti/WEB-INF/classes/lti-config.properties ]; then
+        	echo "Assigning $HOST for LTI integration in ${SERVLET_DIR}/lti/WEB-INF/classes/lti-config.properties"
+        	# We don't wat to guess on http/https as the lti endpoint may be a different BigBlueButton server
+        	sed -i "s/bigbluebuttonURL=http:\/\/.*/bigbluebuttonURL=http:\/\/$HOST\/bigbluebutton/g" \
+          	${SERVLET_DIR}/lti/WEB-INF/classes/lti-config.properties
+        	sed -i "s/bigbluebuttonURL=https:\/\/.*/bigbluebuttonURL=https:\/\/$HOST\/bigbluebutton/g" \
+          	${SERVLET_DIR}/lti/WEB-INF/classes/lti-config.properties
+        	sed -i "s/ltiEndPoint=.*/ltiEndPoint=$HOST/g" \
+          	${SERVLET_DIR}/lti/WEB-INF/classes/lti-config.properties
         fi
 
 
         if [ -f /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml ]; then
-            echo "Assigning $HOST for record and playback in /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml"
-            change_yml_value /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml $redis_host playback_host $HOST
+        	echo "Assigning $HOST for record and playback in /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml"
+        	change_yml_value /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml playback_host $HOST
+          change_yml_value /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml redis_host $redis_host
         fi
-
-        echo -n "Assigning $HOST for playback of recordings: "
-        for metadata in $(find /var/bigbluebutton/published -name metadata.xml); do
-            echo -n "."
-            # Ensure we update both types of URLs
-            sed -i "/<link>/{s/http:\/\/\([^\"\/]*\)\/playback\/$type\([^<]\)/http:\/\/$HOST\/playback\/$type\2/g}" $metadata
-            sed -i "/<link>/{s/https:\/\/\([^\"\/]*\)\/playback\/$type\([^<]\)/https:\/\/$HOST\/playback\/$type\2/g}" $metadata
-        done
-
-        for metadata in $(find /var/bigbluebutton/unpublished -name metadata.xml); do
-            echo -n "."
-            # Ensure we update both types of URLs
-            sed -i "/<link>/{s/http:\/\/\([^\"\/]*\)\/playback\/$type\([^<]\)/http:\/\/$HOST\/playback\/$type\2/g}" $metadata
-            sed -i "/<link>/{s/https:\/\/\([^\"\/]*\)\/playback\/$type\([^<]\)/https:\/\/$HOST\/playback\/$type\2/g}" $metadata
-        done
-        echo
 
         if [ -f /var/www/bigbluebutton/check/conf/config.xml ]; then
-            echo "Assigning $HOST for client self check to /var/www/bigbluebutton/check/conf/config.xml"
-            sed -i "s/rtmp[s]*:\/\/\([^\"\/]*\)\//$PROTOCOL_RTMP:\/\/$HOST\//g" /var/www/bigbluebutton/check/conf/config.xml
-            sed -i "s/rtmpt:\/\/\([^\"\/]*\)\//rtmpt:\/\/$HOST\//g" /var/www/bigbluebutton/check/conf/config.xml
+        	echo "Assigning $HOST for client self check to /var/www/bigbluebutton/check/conf/config.xml"
+        	sed -i "s/rtmp[s]*:\/\/\([^\"\/]*\)\//$PROTOCOL_RTMP:\/\/$HOST\//g" /var/www/bigbluebutton/check/conf/config.xml
+        	sed -i "s/rtmpt:\/\/\([^\"\/]*\)\//rtmpt:\/\/$HOST\//g" /var/www/bigbluebutton/check/conf/config.xml
         fi
-        ###################### Segmento de /usr/bin/bbb-conf ##################################
 
-        # Inicio limpio
-        bbb-conf --clean
+        # Set server ip address in FreeSWITCH
+        sed -i "s@<X-PRE-PROCESS cmd=\"set\" data=\"local_ip_v4=.*\"/>@<X-PRE-PROCESS cmd=\"set\" data=\"local_ip_v4=${bbb_ip}\"/>@g"  $FREESWITCH_VARS
+
+        # Set server ip address in red5 sip app. For flash client.
+        sed -i "s/bbb.sip.app.ip=.*/bbb.sip.app.ip=${bbb_ip}/g" /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
+        sed -i "s/freeswitch.ip=.*/freeswitch.ip=${bbb_ip}/g" /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
+
+        # Enable WebRTC in the client
+        sed -i "s@useWebRTCIfAvailable=\".*\"@useWebRTCIfAvailable=\"true\"@g" /var/www/bigbluebutton/client/conf/config.xml
+
+        # Enable port 5066 in FreeSWITCH
+        sed -i 's/^.*<!--<param name="ws-binding"  value=":5066"\/>-->.*$/\t<param name="ws-binding"  value=":5066"\/>/g' $FREESWITCH_EXTERNAL
+
+        PROTOCOL=$(cat /etc/bigbluebutton/nginx/sip.nginx |  sed -n '/proxy_pass/{s/.*proxy_pass [ ]*//;s/:.*//;p}')
+        PORT=5066
+        if [[ $PROTOCOL == "https" ]]; then
+          PORT=7443
+        fi
+        sed -i "s/proxy_pass .*/proxy_pass $PROTOCOL:\/\/${bbb_ip}:$PORT;/g" /etc/bigbluebutton/nginx/sip.nginx
+        ###################### Fin de segmento de /usr/bin/bbb-conf ##################################
+
+        # Inicio de servicios
+        BBB_SERVICES="red5 tomcat7 nginx freeswitch redis-server bbb-apps-akka bbb-fsesl-akka bbb-record-core.timer libreoffice.service"
+        HTML5=""
+        WEBHOOKS=""
+        if [ -f /usr/lib/systemd/system/bbb-html5.service ]; then
+          HTML5="mongod bbb-html5"
+        fi
+        if [ -f /usr/lib/systemd/system/bbb-webhooks.service ]; then
+          WEBHOOKS=bbb-webhooks
+        fi
+        action=restart
+        systemctl $action $BBB_SERVICES $HTML5 $WEBHOOKS
 
         # Devolver url y llave compartida
-        bbb-conf --secret | grep Salt | awk '{print $2}' > ${heat_outputs_path}.shared_key_out
-        bbb-conf --secret | grep URL | awk '{print $2}' > ${heat_outputs_path}.bbb_url
+        if ! [[ ${is_bbb_demo} == "False" ]]; then
+            DEBIAN_FRONTEND=noninteractive apt -y install bbb-demo
+            echo "$PROTOCOL://$HOST" > ${heat_outputs_path}.bbb_url
+            bbb-conf --secret | grep -i secret: | awk '{print $2}' > ${heat_outputs_path}.shared_key_out
+        else
+          bbb-conf --secret | grep -i url: | awk '{print $2}' > ${heat_outputs_path}.bbb_url
+          bbb-conf --secret | grep -i secret: | awk '{print $2}' > ${heat_outputs_path}.shared_key_out
+        fi
 
   bbb-server-init:
     type: OS::Heat::SoftwareDeployment
@@ -230,6 +291,8 @@ resources:
       server: {get_resource: bbb-server}
       input_values:
          bbb_ip: {get_attr: [bbb-server, networks, {get_param: public_net}, 0]}
+         is_bbb_demo: {get_param: bbb_demo}
+
 
 outputs:
   public_ip:
@@ -246,7 +309,7 @@ outputs:
     value: {get_attr: [bbb-server, name]}
   bbb_url:
     description: >
-      URL de conexión a BBB
+      URL de conexión a API de BBB
     value: {get_attr: [bbb-server-init, bbb_url]}
   bbb_shared_key:
     description: >
